export type LoginTheme = {
  rootBg: string;
  heroGradientFrom: string;
  heroGradientVia: string;
  heroGradientTo: string;
  heroOverlay: string;
  heroLogoPrimary: string;
  heroLogoSecondary: string;
  heroBadgeBg: string;
  heroBadgeBorder: string;
  heroBadgeText: string;
  heroTitle: string;
  heroTitleMuted: string;
  heroAccent: string;
  heroBody: string;
  heroTrustedLabel: string;
  heroTrustedText: string;
  authBg: string;
  authTitle: string;
  authBody: string;
  authLabel: string;
  authMuted: string;
  controlBg: string;
  controlBorder: string;
  controlText: string;
  controlPlaceholder: string;
  divider: string;
  dividerText: string;
  link: string;
  checkboxBg: string;
  checkboxText: string;
  primaryButtonBg: string;
  primaryButtonText: string;
  signUpBg: string;
  signUpBorder: string;
  signUpText: string;
  securityBg: string;
  securityBorder: string;
  securityText: string;
  securityStrong: string;
  footerText: string;
};

export const loginLightTheme: LoginTheme = {
  rootBg: "#ffffff",
  heroGradientFrom: "#0d0d1f",
  heroGradientVia: "#14122e",
  heroGradientTo: "#1f1a38",
  heroOverlay: "rgba(13,13,31,0.78)",
  heroLogoPrimary: "#ffffff",
  heroLogoSecondary: "#ccccd9",
  heroBadgeBg: "rgba(0,199,217,0.08)",
  heroBadgeBorder: "#00c7d9",
  heroBadgeText: "#00c7d9",
  heroTitle: "#ffffff",
  heroTitleMuted: "#d9d9eb",
  heroAccent: "#00c7d9",
  heroBody: "#b8b8c7",
  heroTrustedLabel: "#8c8c9e",
  heroTrustedText: "#d9d9e5",
  authBg: "#ffffff",
  authTitle: "#12141a",
  authBody: "#5c616b",
  authLabel: "#404754",
  authMuted: "#8c919e",
  controlBg: "#ffffff",
  controlBorder: "#d4d9e0",
  controlText: "#12141a",
  controlPlaceholder: "#737885",
  divider: "#d4d9e0",
  dividerText: "#8c91a1",
  link: "#0087a8",
  checkboxBg: "#0d8fb0",
  checkboxText: "#ffffff",
  primaryButtonBg: "#0a7894",
  primaryButtonText: "#ffffff",
  signUpBg: "#ffffff",
  signUpBorder: "#d4d9e0",
  signUpText: "#0a7894",
  securityBg: "#f0fcf0",
  securityBorder: "#b8deba",
  securityText: "#5c616b",
  securityStrong: "#12141a",
  footerText: "#8c919e",
};

export const loginDarkTheme: LoginTheme = {
  rootBg: "#111114",
  heroGradientFrom: "#0d0d1f",
  heroGradientVia: "#14122e",
  heroGradientTo: "#1f1a38",
  heroOverlay: "rgba(13,13,31,0.82)",
  heroLogoPrimary: "#ffffff",
  heroLogoSecondary: "#ccccd9",
  heroBadgeBg: "rgba(0,199,217,0.08)",
  heroBadgeBorder: "#00c7d9",
  heroBadgeText: "#00c7d9",
  heroTitle: "#ffffff",
  heroTitleMuted: "#d9d9eb",
  heroAccent: "#00d1e5",
  heroBody: "#b8b8c7",
  heroTrustedLabel: "#8c8c9e",
  heroTrustedText: "#d9d9e5",
  authBg: "#111115",
  authTitle: "#ffffff",
  authBody: "#9999ad",
  authLabel: "#d9d9e5",
  authMuted: "#8c8c9e",
  controlBg: "#1a1a1f",
  controlBorder: "#383847",
  controlText: "#d9d9e5",
  controlPlaceholder: "#6b6b80",
  divider: "#383847",
  dividerText: "#6b6b80",
  link: "#00d1eb",
  checkboxBg: "#00d1eb",
  checkboxText: "#0a0a0f",
  primaryButtonBg: "#00d1eb",
  primaryButtonText: "#0a0a0f",
  signUpBg: "#1f1f26",
  signUpBorder: "#383847",
  signUpText: "#00d1eb",
  securityBg: "#141f14",
  securityBorder: "#264229",
  securityText: "#a6a6b8",
  securityStrong: "#e0e0ed",
  footerText: "#616173",
};
